//global state 

export const CREATE_NEW_WALLET_ACTIVITY_SPINNER = 'CREATE_NEW_WALLET_ACTIVITY_SPINNER';
export const SET_QI_WALLET_SCAN_IN_PROGRESS = 'SET_QI_WALLET_SCAN_IN_PROGRESS';
export const SET_QI_WALLET_SYNC_IN_PROGRESS = 'SET_QI_WALLET_SYNC_IN_PROGRESS';

export const SET_DATA_LOADER = 'SET_DATA_LOADER';
export const RESET_REDUX_STATE = 'RESET_REDUX_STATE';

// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// user profile

export const SET_USER_ONBOARDED = 'SET_USER_ONBOARDED';
export const SET_USER_AGREED_TERMS = 'SET_USER_AGREED_TERMS';
export const SET_USER_HOME_REGION = 'SET_USER_HOME_REGION';
export const SET_USER_HOME_ZONE = 'SET_USER_HOME_ZONE';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';

//contacts

export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

//Quai wallet

export const CREATE_NEW_QUAI_HD_WALLET = 'CREATE_NEW_QUAI_HD_WALLET';
export const RECOVER_QUAI_HD_WALLET = 'RECOVER_QUAI_HD_WALLET';

export const SET_PRIMARY_WALLET_OBJ = 'SET_PRIMARY_WALLET_OBJ';
export const SET_PRIMARY_WALLET_PUB_ADDR = 'SET_PRIMARY_WALLET_PUB_ADDR';
export const SET_PRIMARY_WALLET_REGION = 'SET_PRIMARY_WALLET_REGION'
export const SET_PRIMARY_WALLET_ZONE = 'SET_PRIMARY_WALLET_ZONE';
export const SET_PRIMARY_WALLET_PKEY_NAME = 'SET_PRIMARY_WALLET_PKEY_NAME';
export const RESET_PRIMARY_WALLET = 'RESET_PRIMARY_WALLET';
export const SET_PRIMARY_WALLET_PHRASE = 'SET_PRIMARY_WALLET_PHRASE';

export const SET_ACTIVE_WALLET_ZONE = 'SET_ACTIVE_WALLET_ZONE';
export const SET_ACTIVE_WALLET_ADDRESS = 'SET_ACTIVE_WALLET_ADDRESS';
export const SET_ACTIVE_WALLET_BALANCE = 'SET_ACTIVE_WALLET_BALANCE';
export const SET_ACTIVE_WALLET_TRANSACTIONS = 'SET_ACTIVE_WALLET_TRANSACTIONS';

export const FETCH_ACTIVE_WALLET_BALANCE = 'FETCH_ACTIVE_WALLET_BALANCE';
export const FETCH_ACTIVE_WALLET_TRANSACTIONS = 'FETCH_ACTIVE_WALLET_TRANSACTIONS';

export const SEND_QUAI_TRANSACTION = 'SEND_QUAI_TRANSACTION';
export const SET_TX_STATUS = 'SET_TX_STATUS';
export const SET_TX_ERROR = 'SET_TX_ERROR';
export const SET_TX_ERROR_MSG = 'SET_TX_ERROR_MSG';


//Qi Wallet

export const CREATE_NEW_QI_HD_WALLET = 'CREATE_NEW_QI_HD_WALLET';
export const RECOVER_QI_HD_WALLET = 'RECOVER_QI_HD_WALLET';

export const SET_PRIMARY_QI_WALLET_OBJ = 'SET_PRIMARY_QI_WALLET_OBJ';
export const SET_PRIMARY_QI_WALLET_ADDR = 'SET_PRIMARY_QI_WALLET_ADDR';
export const SET_PRIMARY_QI_WALLET_REGION = 'SET_PRIMARY_QI_WALLET_REGION'
export const SET_PRIMARY_QI_WALLET_ZONE = 'SET_PRIMARY_QI_WALLET_ZONE';
export const RESET_PRIMARY_QI_WALLET = 'RESET_PRIMARY_QI_WALLET';
export const SET_PRIMARY_QI_WALLET_PHRASE = 'SET_PRIMARY_QI_WALLET_PHRASE';
export const SET_PRIMARY_QI_WALLET_SCANNED = 'SET_PRIMARY_QI_WALLET_SCANNED';
export const SET_PRIMARY_QI_WALLET_SYNCED = 'SET_PRIMARY_QI_WALLET_SYNCED';
export const SET_PRIMARY_QI_WALLET_LAST_SYNCED = 'SET_PRIMARY_QI_WALLET_LAST_SYNCED';

export const SET_ACTIVE_QI_WALLET_ZONE = 'SET_ACTIVE_QI_WALLET_ZONE';
export const SET_ACTIVE_QI_WALLET_ADDRESS = 'SET_ACTIVE_QI_WALLET_ADDRESS';
export const SET_ACTIVE_QI_WALLET_NEXT_ADDRESS = 'SET_ACTIVE_QI_WALLET_NEXT_ADDRESS';
export const SET_ACTIVE_QI_WALLET_ADDRESSES = 'SET_ACTIVE_QI_WALLET_ADDRESSES';
export const SET_ACTIVE_QI_WALLET_GAP_ADDRESSES = 'SET_ACTIVE_QI_WALLET_GAP_ADDRESSES';
export const SET_ACTIVE_QI_WALLET_CHANGE_ADDRESSES = 'SET_ACTIVE_QI_WALLET_CHANGE_ADDRESSES';
export const SET_ACTIVE_QI_WALLET_PAYMENT_CODE = 'SET_ACTIVE_QI_WALLET_PAYMENT_CODE';
export const SET_ACTIVE_QI_WALLET_BALANCE = 'SET_ACTIVE_QI_WALLET_BALANCE';
export const SET_ACTIVE_QI_WALLET_SPENDABLE_BALANCE = 'SET_ACTIVE_QI_WALLET_SPENDABLE_BALANCE';
export const SET_ACTIVE_QI_WALLET_LOCKED_BALANCE = 'SET_ACTIVE_QI_WALLET_LOCKED_BALANCE';
export const SET_ACTIVE_QI_WALLET_TRANSACTIONS = 'SET_ACTIVE_QI_WALLET_TRANSACTIONS';
export const FETCH_ACTIVE_QI_WALLET_BALANCE = 'FETCH_ACTIVE_QI_WALLET_BALANCE';
export const FETCH_ACTIVE_QI_WALLET_TRANSACTIONS = 'FETCH_ACTIVE_QI_WALLET_TRANSACTIONS';
export const SCAN_QI_WALLET = 'SCAN_QI_WALLET';
export const SYNC_QI_WALLET = 'SYNC_QI_WALLET';
export const SEND_QI_TRANSACTION = 'SEND_QI_TRANSACTION';
export const SET_QI_TX_STATUS = 'SET_QI_TX_STATUS';
export const SET_QI_TX_ERROR = 'SET_QI_TX_ERROR';
export const SET_QI_TX_ERROR_MSG = 'SET_TX_ERROR_MSG';


